[font]
normal = { family = "Jetbrains Mono", style = "Regular" }
size = 7

[colors.primary]
background = "#212121"
foreground = "#f1f1f1"

[colors.cursor]
text = "#212121"
cursor = "#f1f1f1"

[colors.vi_mode_cursor]
text = "#212121"
cursor = "#f1f1f1"

[colors.search.matches]
foreground = "#212121"
background = "#f1f1f1"

[colors.search.focused_match]
foreground = "#212121"
background = "#f1f1f1"

[colors.footer_bar]
foreground = "#212121"
background = "#f1f1f1"

[colors.hints.start]
foreground = "#212121"
background = "#f1f1f1"

[colors.hints.end]
foreground = "#212121"
background = "#f1f1f1"

[colors.selection]
text = "#212121"
background = "#f1f1f1"

[colors.normal]
black = "#323a45"
red = "#c62d1f"
green = "#4aa564"
yellow = "#f9aa43"
blue = "#00a6d2"
magenta = "#4c2c92"
cyan = "#4773aa"
white = "#f1f1f1"

[colors.bright]
black = "#323a45"
red = "#c62d1f"
green = "#4aa564"
yellow = "#f9aa43"
blue = "#00a6d2"
magenta = "#4c2c92"
cyan = "#4773aa"
white = "#f1f1f1"

[colors.dim]
black = "#323a45"
red = "#c62d1f"
green = "#4aa564"
yellow = "#f9aa43"
blue = "#00a6d2"
magenta = "#4c2c92"
cyan = "#4773aa"
white = "#f1f1f1"

[[colors.indexed_colors]]
index = 16
color = "#FE640B"

[[colors.indexed_colors]]
index = 17
color = "#DC8A78"
