#!/bin/sh
# Thanks to: i3lock-solarized (https://github.com/parsiad/i3lock-solarized)

# Colors
alpha='dd'
base03='#212121'
base02='#323a45'
base01='#d6d7d9'
base00='#f1f1f1'
base0='#e4e2e0'
base1='#dadada'
base2='#dce4ef'
base3='#aeb0b5'
yellow='#ffc375'
red='#c62d1f'
magenta='#4c2c92'
blue='#00a6d2'
cyan='#94bfa2'
green='#4aa564'


font='Roboto'


# Main command
i3lock \
  --insidever-color=$base02$alpha \
  --insidewrong-color=$base02$alpha \
  --inside-color=$base03$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$base02$alpha \
  --line-uses-ring \
  --keyhl-color=$blue$alpha \
  --bshl-color=$yellow$alpha \
  --separator-color=$base01$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --layout-color=$blue \
  --date-color=$base1 \
  --time-color=$base1 \
  --screen 1 \
  --blur 1 \
  --clock \
  --indicator \
  --keylayout 1 \
  --time-str="%I:%M %p" \
  --date-str="%a, %b %e %Y" \
  --verif-text="Verifying..." \
  --wrong-text="Auth Failed" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --time-font=$font \
  --date-font=$font \
  --layout-font=$font \
  --verif-font=$font \
  --wrong-font=$font \
  --radius=110 \
  --ring-width=9 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
